version: "3"

vars:
  PROTO_SRC: ./proto
  PROTO_DEST: ./api

tasks:
  gen-proto:
    desc: "Compile .proto files into Go files"
    cmds:
      - protoc -I proto {{.PROTO_SRC}}/*.proto --go_out={{.PROTO_DEST}}/ --go_opt=paths=source_relative --go-grpc_out={{.PROTO_DEST}}/ --go-grpc_opt=paths=source_relative

  install-protoc-deps:
    desc: "Install required dependencies for compiling proto files"
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  install-app-deps:
    desc: "Install required dependencies for running app"
    cmds:
      - go get -u google.golang.org/grpc
      - go get -u github.com/ilyakaznacheev/cleanenv
      - go get -u github.com/grpc-ecosystem/go-grpc-middleware/v2