version: "3"

vars:
  PROTO_SRC: ./proto
  PROTO_DEST: ./api
  BIN_DEST: ./bin

tasks:
  build:
    desc: "Build project into a binary"
    silent: true
    cmds:
      - go build -o {{.BIN_DEST}}/stash ./cmd/server/main.go

  clean:
    desc: "Removes {{.BIN_DEST}} direcotry"
    silent: true
    cmds:
      - rm -r {{.BIN_DEST}}    

  gen-proto:
    desc: "Compile .proto files into Go files"
    silent: true
    cmds:
      - protoc -I proto {{.PROTO_SRC}}/*.proto --go_out={{.PROTO_DEST}}/ --go_opt=paths=source_relative --go-grpc_out={{.PROTO_DEST}}/ --go-grpc_opt=paths=source_relative

  install-protoc-deps:
    desc: "Install required dependencies for compiling proto files"
    silent: true
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest