# settings for grpc service
grpc:
  port: 1234
  timeout: "5s" # ???
  sync-node: "addr0"
  nodes:
    - "addr1"
    - "addr2"
    - "addr3"

# settings for cas
cas:
  path: "stash" # path to stash cas on local machine
  compression-level: 1 # later...
  allow-server-side-compression: false


