env: "dev"
grpc:
  port: 5555
  timeout: "5s" # ???
  sync-node: ":5656"
#  nodes:
#    - ":5556"
#    - ":5557"
#    - ":5558"
cas:
  path: "stash" # path to stash cas on local machine
  compression-level: 1 # later...
  replication-factor: 0 # how many times replicate
  allow-server-side-compression: false


